import Link from "@/components/Link";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My car Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Link/>
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
    </html>
  );
}
